services:
  bahnhof-server:
    image: ghcr.io/tramlines-pt/bahnhof-server:main
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]
    restart: always
    environment:
      DB_CLIENT_ID: "client_id"
      DB_CLIENT_SECRET: "client_secret"
    dns:
      - 1.1.1.1
      - 1.0.0.1