services:
  bahnhof-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]
    restart: always
    environment:
      DB_CLIENT_ID: "client_id"
      DB_CLIENT_SECRET: "client_secret"
    dns:
      - 1.1.1.1
      - 1.0.0.1